### ISSUE TITLE
User should be able to load csv or tsv data sets

### ISSUE THREAD

**Issue by NickStefan** [decisive-wizard/GridHub#3]

**Comment by NickStefan** [comment]
should be able to access filesystem using node webkit:
https://github.com/rogerwang/node-webkit/wiki/Getting-Started-with-node-webkit
http://code.tutsplus.com/tutorials/introduction-to-html5-desktop-apps-with-node-webkit--net-36296

**Comment by johnheroy** [comment]
Working on loading .csv to complete the other half of the 'open file' and then edit spreadsheet user story
